# Generated by Django 2.0.3 on 2018-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Connected'), ('SA', 'Seeker Accepted'), ('SR', 'Seeker Rejected'), ('PR', 'Posted Rejected')], max_length=2)),
            ],
        ),
    ]
