# Generated by Django 2.0.3 on 2018-03-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_history'),
        ('seekers', '0005_remove_seeker_history'),
        ('job_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='seeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seekers.Seeker'),
            preserve_default=False,
        ),
    ]
