# Generated by Django 2.0.3 on 2018-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('wage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_text', models.CharField(max_length=200)),
                ('skills', models.ManyToManyField(to='skills.Skill')),
            ],
        ),
    ]
