# Generated by Django 2.0.3 on 2018-03-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_remove_poster_jobs'),
        ('jobs', '0003_job_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posters.Poster'),
            preserve_default=False,
        ),
    ]
