# Generated by Django 2.0.3 on 2018-03-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='history',
        ),
    ]
