# Generated by Django 2.0.3 on 2018-03-09 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='seeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seekers.Seeker'),
        ),
    ]
