# Generated by Django 2.0.3 on 2018-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='language',
            field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French'), ('IT', 'Italian'), ('ES', 'Spanish')], default='EN', max_length=2),
            preserve_default=False,
        ),
    ]
