# Generated by Django 2.0.3 on 2018-03-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_poster_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='jobs',
        ),
    ]
