# Generated by Django 2.0.3 on 2018-03-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_remove_poster_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='phone_number',
        ),
    ]
