# Generated by Django 2.0.3 on 2018-03-09 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_history', '0001_initial'),
        ('seekers', '0002_auto_20180309_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_history.JobHistory'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='language',
            field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French'), ('IT', 'Italian'), ('ES', 'Spanish')], default='EN', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='last_job_accepted',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
