# Generated by Django 2.0.3 on 2018-03-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0004_remove_seeker_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='history',
        ),
    ]
