# Generated by Django 2.0.3 on 2018-03-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0005_remove_seeker_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='phone_number',
        ),
    ]
